fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    subtitle
    title
    description
    candleMessages
  }
  googleDeathSection {
    __typename
    title
    paragraph
    checkboxItems {
      __typename
      text
    }
    closingPhrase
  }
  painPointsSection {
    __typename
    title
    subtitleFirstPart
    phrases {
      __typename
      leftPart
      rightPart
    }
    closingPhrase
  }
  transitionMessageSection {
    __typename
    mainText
    highlightedText
    continuationText
    secondaryText
  }
  bridgeSection {
    __typename
    title
    paragraph
  }
  servicesPackagesSection {
    __typename
    title
    packages {
      __typename
      icon
      heading
      description
      deliverables
      ctaText
      ctaLink
    }
    finalCta {
      __typename
      text
      linkText
      linkUrl
    }
  }
  statsSection {
    __typename
    title
    subtitle
    stats {
      __typename
      value
      suffix
      description
    }
  }
  ctaSection {
    __typename
    title
    description
    buttonText
    buttonLink
  }
}

fragment PostParts on Post {
  __typename
  title
  description
  pubDate
  heroImage
  tags
  metaTitle
  body
}

fragment PagesParts on Pages {
  __typename
  title
  description
  subtitle
  introduction
  profileImage
  experienceSection {
    __typename
    title
    subtitle
    items {
      __typename
      icon
      title
      description
    }
  }
  valuesSection {
    __typename
    title
    subtitle
    values {
      __typename
      title
      description
    }
  }
  testimonial {
    __typename
    quote
    author
    role
  }
  ctaSection {
    __typename
    title
    description
    buttonText
  }
  body
}
